[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["cd api && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"