providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python --version",
    "which python",
    "pip --version",
    "which pip",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[start]
cmd = "cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"