[build]
builder = "nixpacks"
watchPatterns = ["api/**"]
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd api && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[environments.production]
variables = {
  PYTHON_VERSION = "3.11",
  PORT = "8000"
}